\set ON_ERROR_STOP on
\if :{?dataset_script_sha256}
\else
\set dataset_script_sha256 'not-provided'
\endif

SET client_min_messages = warning;
SET statement_timeout = 0;
SET lock_timeout = '10s';
SET timezone = 'Asia/Shanghai';
SET maintenance_work_mem = '256MB';

BEGIN;

COMMENT ON DATABASE rw_proxy_lab IS
  'Deterministic business test database for PostgreSQL and Pgpool validation';

CREATE SCHEMA business AUTHORIZATION postgres;
COMMENT ON SCHEMA business IS
  'Repeatable synthetic business dataset generated by primary-test-data.sql';

CREATE TABLE business.customers (
  customer_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_no varchar(16) NOT NULL UNIQUE,
  full_name varchar(80) NOT NULL,
  phone varchar(20) NOT NULL,
  email varchar(120) NOT NULL,
  region_code char(6) NOT NULL,
  customer_tier smallint NOT NULL CHECK (customer_tier BETWEEN 1 AND 5),
  account_status varchar(16) NOT NULL
    CHECK (account_status IN ('active', 'suspended')),
  credit_limit numeric(14,2) NOT NULL CHECK (credit_limit >= 0),
  registered_at timestamptz NOT NULL
);

CREATE TABLE business.products (
  product_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sku varchar(20) NOT NULL UNIQUE,
  product_name varchar(120) NOT NULL,
  category_code varchar(24) NOT NULL,
  list_price numeric(12,2) NOT NULL CHECK (list_price > 0),
  cost_price numeric(12,2) NOT NULL CHECK (cost_price > 0),
  is_active boolean NOT NULL,
  created_at timestamptz NOT NULL
);

CREATE TABLE business.orders (
  order_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_no varchar(24) NOT NULL UNIQUE,
  customer_id bigint NOT NULL REFERENCES business.customers(customer_id),
  order_status varchar(16) NOT NULL
    CHECK (order_status IN ('created', 'paid', 'shipped', 'completed', 'cancelled')),
  sales_channel varchar(16) NOT NULL
    CHECK (sales_channel IN ('web', 'app', 'store', 'partner')),
  region_code char(6) NOT NULL,
  ordered_at timestamptz NOT NULL,
  paid_at timestamptz,
  total_amount numeric(16,2) NOT NULL DEFAULT 0 CHECK (total_amount >= 0),
  row_version integer NOT NULL DEFAULT 1 CHECK (row_version > 0),
  updated_at timestamptz NOT NULL,
  remark varchar(200)
);

CREATE TABLE business.order_items (
  order_item_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id bigint NOT NULL REFERENCES business.orders(order_id) ON DELETE CASCADE,
  line_no smallint NOT NULL CHECK (line_no BETWEEN 1 AND 99),
  product_id bigint NOT NULL REFERENCES business.products(product_id),
  quantity integer NOT NULL CHECK (quantity > 0),
  unit_price numeric(12,2) NOT NULL CHECK (unit_price > 0),
  line_amount numeric(16,2) NOT NULL CHECK (line_amount > 0),
  UNIQUE (order_id, line_no)
);

CREATE TABLE business.rw_probe (
  probe_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  probe_key varchar(80) NOT NULL,
  payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT clock_timestamp()
);
COMMENT ON TABLE business.rw_probe IS
  'Empty table reserved for later read/write routing tests';

CREATE TABLE business.dataset_manifest (
  dataset_version varchar(40) PRIMARY KEY,
  generator_sha256 varchar(64) NOT NULL,
  generated_at timestamptz NOT NULL,
  customer_rows bigint NOT NULL,
  product_rows bigint NOT NULL,
  order_rows bigint NOT NULL,
  order_item_rows bigint NOT NULL,
  deterministic boolean NOT NULL
);

INSERT INTO business.customers (
  customer_id,
  customer_no,
  full_name,
  phone,
  email,
  region_code,
  customer_tier,
  account_status,
  credit_limit,
  registered_at
)
SELECT
  g,
  'C' || lpad(g::text, 10, '0'),
  '测试客户-' || lpad(g::text, 6, '0'),
  '1' || lpad((3000000000::bigint + g)::text, 10, '0'),
  'customer' || g || '@example.test',
  (ARRAY['110000', '310000', '440100', '440300', '320100', '330100', '420100', '510100'])
    [1 + ((g - 1) % 8)],
  (1 + ((g - 1) % 5))::smallint,
  CASE WHEN g % 20 = 0 THEN 'suspended' ELSE 'active' END,
  (5000 + (g % 200) * 250)::numeric(14,2),
  timestamptz '2023-01-01 00:00:00+08'
    + ((g - 1) % 900) * interval '1 day'
    + (g % 86400) * interval '1 second'
FROM generate_series(1, 30000) AS series(g);

INSERT INTO business.products (
  product_id,
  sku,
  product_name,
  category_code,
  list_price,
  cost_price,
  is_active,
  created_at
)
SELECT
  g,
  'SKU' || lpad(g::text, 8, '0'),
  '测试商品-' || lpad(g::text, 5, '0'),
  (ARRAY['digital', 'office', 'home', 'food', 'clothing', 'sports'])
    [1 + ((g - 1) % 6)],
  round((10 + (g % 500) * 1.25)::numeric, 2),
  round(((10 + (g % 500) * 1.25) * 0.62)::numeric, 2),
  g % 40 <> 0,
  timestamptz '2022-01-01 00:00:00+08' + (g % 730) * interval '1 day'
FROM generate_series(1, 2000) AS series(g);

WITH generated_orders AS (
  SELECT
    g,
    timestamptz '2024-01-01 00:00:00+08'
      + ((g - 1) % 730) * interval '1 day'
      + (g % 1440) * interval '1 minute' AS ordered_at,
    CASE
      WHEN g % 20 < 2 THEN 'cancelled'
      WHEN g % 20 < 5 THEN 'created'
      WHEN g % 20 < 9 THEN 'paid'
      WHEN g % 20 < 14 THEN 'shipped'
      ELSE 'completed'
    END AS order_status
  FROM generate_series(1, 150000) AS series(g)
)
INSERT INTO business.orders (
  order_id,
  order_no,
  customer_id,
  order_status,
  sales_channel,
  region_code,
  ordered_at,
  paid_at,
  total_amount,
  row_version,
  updated_at,
  remark
)
SELECT
  g,
  'O' || lpad(g::text, 14, '0'),
  1 + ((g - 1) % 30000),
  order_status,
  (ARRAY['web', 'app', 'store', 'partner'])[1 + ((g - 1) % 4)],
  (ARRAY['110000', '310000', '440100', '440300', '320100', '330100', '420100', '510100'])
    [1 + ((g - 1) % 8)],
  ordered_at,
  CASE
    WHEN order_status IN ('created', 'cancelled') THEN NULL
    ELSE ordered_at + (15 + (g % 720)) * interval '1 minute'
  END,
  0,
  1 + (g % 7),
  ordered_at + (30 + (g % 2880)) * interval '1 minute',
  CASE WHEN g % 50 = 0 THEN '批量测试订单-' || g ELSE NULL END
FROM generated_orders;

INSERT INTO business.order_items (
  order_item_id,
  order_id,
  line_no,
  product_id,
  quantity,
  unit_price,
  line_amount
)
SELECT
  (o.order_id - 1) * 3 + line.line_no,
  o.order_id,
  line.line_no,
  p.product_id,
  (1 + ((o.order_id + line.line_no) % 5))::integer,
  p.list_price,
  round(p.list_price * (1 + ((o.order_id + line.line_no) % 5)), 2)
FROM business.orders AS o
CROSS JOIN generate_series(1, 3) AS line(line_no)
JOIN business.products AS p
  ON p.product_id = 1 + ((o.order_id * 17 + line.line_no * 13 - 1) % 2000);

UPDATE business.orders AS o
SET total_amount = totals.total_amount
FROM (
  SELECT order_id, sum(line_amount)::numeric(16,2) AS total_amount
  FROM business.order_items
  GROUP BY order_id
) AS totals
WHERE totals.order_id = o.order_id;

SELECT setval(
  pg_get_serial_sequence('business.customers', 'customer_id'),
  (SELECT max(customer_id) FROM business.customers),
  true
);
SELECT setval(
  pg_get_serial_sequence('business.products', 'product_id'),
  (SELECT max(product_id) FROM business.products),
  true
);
SELECT setval(
  pg_get_serial_sequence('business.orders', 'order_id'),
  (SELECT max(order_id) FROM business.orders),
  true
);
SELECT setval(
  pg_get_serial_sequence('business.order_items', 'order_item_id'),
  (SELECT max(order_item_id) FROM business.order_items),
  true
);

CREATE INDEX customers_region_tier_idx
  ON business.customers(region_code, customer_tier);
CREATE INDEX orders_customer_time_idx
  ON business.orders(customer_id, ordered_at DESC);
CREATE INDEX orders_status_time_idx
  ON business.orders(order_status, ordered_at DESC);
CREATE INDEX orders_region_time_idx
  ON business.orders(region_code, ordered_at DESC);
CREATE INDEX order_items_product_idx
  ON business.order_items(product_id);

INSERT INTO business.dataset_manifest (
  dataset_version,
  generator_sha256,
  generated_at,
  customer_rows,
  product_rows,
  order_rows,
  order_item_rows,
  deterministic
)
VALUES (
  'business-v1',
  :'dataset_script_sha256',
  clock_timestamp(),
  30000,
  2000,
  150000,
  450000,
  true
);

DO $validation$
BEGIN
  IF (SELECT count(*) FROM business.customers) <> 30000 THEN
    RAISE EXCEPTION 'unexpected customer row count';
  END IF;
  IF (SELECT count(*) FROM business.products) <> 2000 THEN
    RAISE EXCEPTION 'unexpected product row count';
  END IF;
  IF (SELECT count(*) FROM business.orders) <> 150000 THEN
    RAISE EXCEPTION 'unexpected order row count';
  END IF;
  IF (SELECT count(*) FROM business.order_items) <> 450000 THEN
    RAISE EXCEPTION 'unexpected order-item row count';
  END IF;
  IF EXISTS (SELECT 1 FROM business.orders WHERE total_amount <= 0) THEN
    RAISE EXCEPTION 'order with non-positive total found';
  END IF;
  IF EXISTS (
    SELECT 1
    FROM business.order_items AS i
    LEFT JOIN business.orders AS o ON o.order_id = i.order_id
    WHERE o.order_id IS NULL
  ) THEN
    RAISE EXCEPTION 'orphan order item found';
  END IF;
END
$validation$;

COMMIT;

VACUUM (ANALYZE) business.customers;
VACUUM (ANALYZE) business.products;
VACUUM (ANALYZE) business.orders;
VACUUM (ANALYZE) business.order_items;
ANALYZE business.rw_probe;
ANALYZE business.dataset_manifest;

SELECT 'customers' AS table_name,
       count(*) AS row_count,
       pg_size_pretty(pg_total_relation_size('business.customers')) AS total_size
FROM business.customers
UNION ALL
SELECT 'products', count(*), pg_size_pretty(pg_total_relation_size('business.products'))
FROM business.products
UNION ALL
SELECT 'orders', count(*), pg_size_pretty(pg_total_relation_size('business.orders'))
FROM business.orders
UNION ALL
SELECT 'order_items', count(*), pg_size_pretty(pg_total_relation_size('business.order_items'))
FROM business.order_items
ORDER BY table_name;
