#!/usr/bin/env bash

set -Eeuo pipefail
IFS=$'\n\t'

ROOT="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/../.." && pwd)"
readiness_script="${ROOT}/scripts/05-readiness-check.sh"
configure_script="${ROOT}/scripts/10-configure-primary.sh"

for script_file in "${readiness_script}" "${configure_script}"; do
  script_text="$(tr '[:upper:]' '[:lower:]' <"${script_file}")"
  [[ "${script_text}" == *"a.attname='probe_id' and a.atttypid='bigint'::regtype and a.attnotnull and a.attidentity='d'"* ]] || {
      printf 'probe_id 未按 PostgreSQL identity-by-default 目录语义校验: %s\n' "${script_file}" >&2
      exit 1
    }
  while IFS= read -r script_line; do
    script_line="${script_line,,}"
    if [[ "${script_line}" == *"attname='probe_id'"* && "${script_line}" == *'atthasdef'* ]]; then
      printf 'probe_id 被错误地按 atthasdef 校验: %s\n' "${script_file}" >&2
      exit 1
    fi
  done <"${script_file}"
done

[[ "$(<"${configure_script}")" == *'probe_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY'* ]]
[[ "$(<"${configure_script}")" == *'actual_structure'* ]]
[[ "$(<"${readiness_script}")" == *'实际目录='* ]]

printf 'PROBE_IDENTITY_CONTRACT_OK\n'
